export const vehicleSpecs = [
  // ========== 718 Cayman ==========
  {
    specId: 's1',
    vehicleId: 'v001',
    specName: 'Fuel Type',
    specValue: 'Gasoline',
    displayOrder: 0,
    groupName: 'General',
  },
  {
    specId: 's1b',
    vehicleId: 'v001',
    specName: 'Seats',
    specValue: '2',
    displayOrder: 1,
    groupName: 'General',
  },
  {
    specId: 's2',
    vehicleId: 'v001',
    specName: 'Acceleration 0 - 100 km/h',
    specValue: '4.9 s',
    displayOrder: 2,
    groupName: 'GeneralPerformance',
  },
  {
    specId: 's3',
    vehicleId: 'v001',
    specName: 'Power (kW / PS)',
    specValue: '220 kW / 300 PS',
    displayOrder: 3,
    groupName: 'GeneralPerformance',
  },
  {
    specId: 's4',
    vehicleId: 'v001',
    specName: 'Top speed',
    specValue: '275 km/h',
    displayOrder: 4,
    groupName: 'GeneralPerformance',
  },

  // --- Technical Details (Drawer content) ---
  // Power Unit
  {
    specId: 't1',
    vehicleId: 'v001',
    specName: 'Number of cylinders',
    specValue: '4',
    groupName: 'Power unit',
  },
  {
    specId: 't2',
    vehicleId: 'v001',
    specName: 'Bore',
    specValue: '91.0 mm',
    groupName: 'Power unit',
  },
  {
    specId: 't3',
    vehicleId: 'v001',
    specName: 'Stroke',
    specValue: '76.4 mm',
    groupName: 'Power unit',
  },
  {
    specId: 't4',
    vehicleId: 'v001',
    specName: 'Displacement',
    specValue: '1,988 cm³',
    groupName: 'Power unit',
  },
  {
    specId: 't5',
    vehicleId: 'v001',
    specName: 'Power (kW)',
    specValue: '220 kW',
    groupName: 'Power unit',
  },
  {
    specId: 't6',
    vehicleId: 'v001',
    specName: 'Power (PS)',
    specValue: '300 PS',
    groupName: 'Power unit',
  },
  {
    specId: 't7',
    vehicleId: 'v001',
    specName: 'Maximum engine speed',
    specValue: '7,500 1/min',
    groupName: 'Power unit',
  },
  {
    specId: 't8',
    vehicleId: 'v001',
    specName: 'Max. output per liter (kW/l)',
    specValue: '111.00',
    groupName: 'Power unit',
  },
  {
    specId: 't9',
    vehicleId: 'v001',
    specName: 'Max. output per liter (PS/l)',
    specValue: '150.00',
    groupName: 'Power unit',
  },

  // Performance
  {
    specId: 't10',
    vehicleId: 'v001',
    specName: 'Top speed',
    specValue: '275 km/h',
    groupName: 'Performance',
  },
  {
    specId: 't11',
    vehicleId: 'v001',
    specName: 'Acceleration 0 - 100 km/h',
    specValue: '4.9 s',
    groupName: 'Performance',
  },
  {
    specId: 't12',
    vehicleId: 'v001',
    specName: 'Acceleration 0 - 100 km/h (Sport Chrono)',
    specValue: '4.7 s',
    groupName: 'Performance',
  },
  {
    specId: 't13',
    vehicleId: 'v001',
    specName: 'Acceleration 0 - 160 km/h',
    specValue: '11.1 s',
    groupName: 'Performance',
  },
  {
    specId: 't14',
    vehicleId: 'v001',
    specName: 'Acceleration 0 - 160 km/h (Sport Chrono)',
    specValue: '10.8 s',
    groupName: 'Performance',
  },
  {
    specId: 't15',
    vehicleId: 'v001',
    specName: 'Acceleration 0 - 200 km/h',
    specValue: '18.1 s',
    groupName: 'Performance',
  },
  {
    specId: 't16',
    vehicleId: 'v001',
    specName: 'Acceleration 0 - 200 km/h (Sport Chrono)',
    specValue: '17.8 s',
    groupName: 'Performance',
  },
  {
    specId: 't17',
    vehicleId: 'v001',
    specName: 'In-gear acceleration (80–120km/h)',
    specValue: '3.2 s',
    groupName: 'Performance',
  },

  // Consumption/Emissions
  {
    specId: 't18',
    vehicleId: 'v001',
    specName: 'Fuel consumption urban',
    specValue: '11.8 l/100 km',
    groupName: 'Consumption/Emissions',
  },
  {
    specId: 't19',
    vehicleId: 'v001',
    specName: 'Fuel consumption extra-urban',
    specValue: '6.8 l/100 km',
    groupName: 'Consumption/Emissions',
  },
  {
    specId: 't20',
    vehicleId: 'v001',
    specName: 'Fuel consumption combined',
    specValue: '8.6 l/100 km',
    groupName: 'Consumption/Emissions',
  },
  {
    specId: 't21',
    vehicleId: 'v001',
    specName: 'CO₂ emissions combined',
    specValue: '197 g/km',
    groupName: 'Consumption/Emissions',
  },

  // Sound level
  {
    specId: 't22',
    vehicleId: 'v001',
    specName: 'Sound level (stationary)',
    specValue: '89 dB(A)',
    groupName: 'Sound level',
  },
  {
    specId: 't23',
    vehicleId: 'v001',
    specName: 'Sound level rpm',
    specValue: '3,750 1/min',
    groupName: 'Sound level',
  },
  {
    specId: 't24',
    vehicleId: 'v001',
    specName: 'Sound level (passing vehicle)',
    specValue: '69 dB(A)',
    groupName: 'Sound level',
  },

  // Body
  {
    specId: 't25',
    vehicleId: 'v001',
    specName: 'Length',
    specValue: '4,379 mm',
    groupName: 'Body',
  },
  {
    specId: 't26',
    vehicleId: 'v001',
    specName: 'Width',
    specValue: '1,801 mm',
    groupName: 'Body',
  },
  {
    specId: 't27',
    vehicleId: 'v001',
    specName: 'Width (with mirrors)',
    specValue: '1,994 mm',
    groupName: 'Body',
  },
  {
    specId: 't28',
    vehicleId: 'v001',
    specName: 'Height',
    specValue: '1,295 mm',
    groupName: 'Body',
  },
  {
    specId: 't29',
    vehicleId: 'v001',
    specName: 'Wheelbase',
    specValue: '2,475 mm',
    groupName: 'Body',
  },
  {
    specId: 't30',
    vehicleId: 'v001',
    specName: 'Unladen weight (DIN)',
    specValue: '1,365 kg',
    groupName: 'Body',
  },
  {
    specId: 't31',
    vehicleId: 'v001',
    specName: 'Unladen weight (EU)',
    specValue: '1,440 kg',
    groupName: 'Body',
  },
  {
    specId: 't32',
    vehicleId: 'v001',
    specName: 'Permissible gross weight',
    specValue: '1,685 kg',
    groupName: 'Body',
  },
  {
    specId: 't33',
    vehicleId: 'v001',
    specName: 'Maximum load',
    specValue: '320 kg',
    groupName: 'Body',
  },

  // Capacities
  {
    specId: 't34',
    vehicleId: 'v001',
    specName: 'Luggage compartment front',
    specValue: '150 l',
    groupName: 'Capacities',
  },
  {
    specId: 't35',
    vehicleId: 'v001',
    specName: 'Open luggage compartment (behind front seats)',
    specValue: '184 l',
    groupName: 'Capacities',
  },
  {
    specId: 't36',
    vehicleId: 'v001',
    specName: 'Largest luggage compartment (to roof)',
    specValue: '272 l',
    groupName: 'Capacities',
  },

  // 718 Boxster
  {
    specId: 's5',
    vehicleId: 'v002',
    specName: 'Fuel Type',
    specValue: 'Gasoline',
    displayOrder: 0,
    groupName: 'General',
  },
  {
    specId: 's5b',
    vehicleId: 'v002',
    specName: 'Seats',
    specValue: '2',
    displayOrder: 1,
    groupName: 'General',
  },
  {
    specId: 's6',
    vehicleId: 'v002',
    specName: 'Acceleration 0 - 100 km/h',
    specValue: '4.9 s',
    displayOrder: 2,
    groupName: 'GeneralPerformance',
  },
  {
    specId: 's7',
    vehicleId: 'v002',
    specName: 'Power (kW / PS)',
    specValue: '220 kW / 300 PS',
    displayOrder: 3,
    groupName: 'GeneralPerformance',
  },
  {
    specId: 's8',
    vehicleId: 'v002',
    specName: 'Top speed',
    specValue: '275 km/h',
    displayOrder: 4,
    groupName: 'GeneralPerformance',
  },

  // 718 Cayman Style Edition
  {
    specId: 's9',
    vehicleId: 'v003',
    specName: 'Fuel Type',
    specValue: 'Gasoline',
    displayOrder: 0,
    groupName: 'General',
  },
  {
    specId: 's9b',
    vehicleId: 'v003',
    specName: 'Seats',
    specValue: '2',
    displayOrder: 1,
    groupName: 'General',
  },
  {
    specId: 's10',
    vehicleId: 'v003',
    specName: 'Acceleration 0 - 100 km/h',
    specValue: '4.9 s',
    displayOrder: 2,
    groupName: 'GeneralPerformance',
  },
  {
    specId: 's11',
    vehicleId: 'v003',
    specName: 'Power (kW / PS)',
    specValue: '220 kW / 300 PS',
    displayOrder: 3,
    groupName: 'GeneralPerformance',
  },
  {
    specId: 's12',
    vehicleId: 'v003',
    specName: 'Top speed',
    specValue: '275 km/h',
    displayOrder: 4,
    groupName: 'GeneralPerformance',
  },
];
